export const copy = {
  en: {
    badge: 'Muzaffarpur Labor Hub',
    headline: 'Simple hiring and job matching for Muzaffarpur',
    subheadline:
      'A clean customer and labour platform with Bhojpuri, Hindi, posting, matching, ratings, and chat-ready sections.',
    login: 'Login',
    signup: 'Sign Up',
    customer: 'Customer',
    labour: 'Labour',
    roleTitle: 'Choose account type',
    customerRoleBody: 'Post jobs, find skilled labour, and hire faster.',
    labourRoleBody: 'Manage profile, skills, availability, and matching jobs.',
    welcomeBack: 'Welcome back',
    createAccount: 'Create account',
    loginDescription: 'Login with only the essential details and go straight to your dashboard.',
    signupDescription: 'Register quickly and continue with the right tools for your role.',
    fullName: 'Full name',
    fullNamePlaceholder: 'Enter your full name',
    email: 'Email address',
    emailPlaceholder: 'Enter your email',
    phone: 'Phone number',
    phonePlaceholder: 'Enter your phone number',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    submitLogin: 'Open Dashboard',
    submitSignup: 'Create Account',
    switchToLogin: 'Already have an account? Login',
    switchToSignup: 'Need an account? Create one',
    demoButton: 'Open Demo',
    back: 'Back',
    needWorkers: 'I need workers',
    offerServices: 'I offer services',
    customerRoleDescription: 'Post your project details and quickly connect with millions, helpers, electricians, plumbers, and more in your area.',
    labourRoleDescription: 'Build a strong profile for your work, highlight your skills, and get discovered by customers looking for reliable local professionals.',
    startHiring: 'Start Hiring',
    signUpWorker: 'Sign up as a worker',
    allCitiesAvailable: 'Available in Muzaffarpur',
    footerBenefits: 'Live opportunities in Muzaffarpur • Better worker-employer matching • Professional first impression',
    envTitle: 'Single API configuration',
    envBody: 'Set EXPO_PUBLIC_API_URL once in your .env file and keep your API calls clean.',
    missingTitle: 'Missing information',
    missingBody: 'Please fill the required fields before continuing.',
    successTitle: 'Success',
    loginSuccess: 'Login completed successfully.',
    signupSuccess: 'Signup completed successfully.',
    errorTitle: 'Request failed',
    logout: 'Logout',
    customerDashboardBadge: 'Customer Home',
    labourDashboardBadge: 'Labour Dashboard',
    hello: 'Hello',
    customerSubtitle:
      'Search labour by skill, area, and availability, then post work in a clean simple flow.',
    labourSubtitle:
      'Update skills, keep your profile neat, and browse matching jobs near Muzaffarpur.',
    activeLabours: 'Available labour',
    liveJobs: 'Live jobs',
    avgRating: 'Avg rating',
    hiresToday: 'Hires today',
    matchesToday: 'Matches today',
    profileViews: 'Profile views',
    completedJobs: 'Completed jobs',
    responseRate: 'Response rate',
    filtersTitle: 'Filters',
    searchPlaceholder: 'Search by skill, name, or area',
    district: 'City / Area',
    category: 'Skill',
    availability: 'Availability',
    rating: 'Rating',
    clearFilters: 'Clear filters',
    availableLaboursTitle: 'Available labour in Muzaffarpur',
    noLabours: 'No labour found for the current filters.',
    popularSkillsTitle: 'Popular skills',
    postJobTitle: 'Post a job',
    postJobOpen: 'Post Job',
    jobTitle: 'Job title',
    jobTitlePlaceholder: 'Need Raj Mistri for 2 hours',
    requiredSkill: 'Required skill',
    dateTime: 'Date and time',
    dateTimePlaceholder: 'Today, 4:00 PM',
    locationLabel: 'Location',
    locationPlaceholder: 'Motijheel, Bela, Muzaffarpur...',
    description: 'Job description',
    descriptionPlaceholder: 'Write the work details clearly',
    skillLevel: 'Skill level',
    postJobButton: 'Publish Job',
    close: 'Close',
    profileTitle: 'Labour profile',
    skillsTitle: 'Skills and certifications',
    preferencesTitle: 'Availability and preferences',
    reviewsTitle: 'Ratings and reviews',
    workHistoryTitle: 'Work history',
    jobRequestsTitle: 'Posted jobs for labour',
    availableJobsTitle: 'Available jobs',
    updateSkills: 'Update Skills',
    editProfile: 'Edit Profile',
    applicantsLabel: 'Applicants',
    postedLabel: 'Posted',
    distanceLabel: 'Distance',
    hireNow: 'Hire Now',
    applyNow: 'Apply Now',
    applied: 'Applied',
    ratingLabel: 'Rating',
    save: 'Save',
    cancel: 'Cancel',
    namePlaceholder: 'Enter your name',
    titlePlaceholder: 'Enter your job title',
    locationPlaceholder: 'Enter your location',
    phonePlaceholder: 'Enter your phone number',
    profileUpdatedTitle: 'Profile Updated',
    profileUpdatedMessage: 'Your profile has been updated successfully.',
    apply: 'Apply',
    applyConfirmTitle: 'Apply for Job',
    applyConfirmMessage: 'Are you sure you want to apply for "{job}"?',
    alreadyAppliedTitle: 'Already Applied',
    alreadyAppliedMessage: 'You have already applied for this job.',
    applicationSuccessTitle: 'Application Submitted',
    applicationSuccessMessage: 'Your application has been submitted successfully.',
    applicationSubmitted: 'Application submitted for {job}',
    todayWorkButton: 'Today Work',
    todayWorkConfirmTitle: 'Request Today Work',
    todayWorkConfirmMessage: 'Your job offer will be confirmed within 15 minutes. Continue?',
    confirm: 'Confirm',
    todayWorkSuccessTitle: 'Request Submitted',
    todayWorkSuccessMessage: 'Your today work request has been submitted.',
    todayWorkNotification: 'Today work request submitted - confirmation within 15 minutes',
    notificationsTitle: 'Notifications',
    notifyTitle: 'Notifications',
    notifyCustomer: 'Get alerts when a labour responds, job is accepted, or someone becomes available nearby.',
    notifyLabour: 'Get alerts when a new job matches your skill and preferred time.',
    focusMuzaffarpur: 'Primary area: Muzaffarpur',
    focusMuzaffarpurBody:
      'The platform highlights jobs and labour around Muzaffarpur first, with simple city-based filters.',
    messengerTitle: 'Chat and messages',
    messengerCustomer: 'Chat directly with labour after shortlisting or hiring.',
    messengerLabour: 'Reply to customers directly when jobs match your skill.',
    jobPostedTitle: 'Job posted',
    jobPostedBody: 'Your job is now visible for nearby labour.',
    today: 'Today',
    tomorrow: 'Tomorrow',
    specificDate: 'Specific Date',
  },
  hi: {
    badge: 'Muzaffarpur Labor Hub',
    headline: 'Muzaffarpur ke liye saaf aur asaan hiring platform',
    subheadline:
      'Customer aur labour dono ke liye clean login, job posting, matching, rating aur chat-ready sections.',
    login: 'Login',
    signup: 'Signup',
    customer: 'Customer',
    labour: 'Labour',
    roleTitle: 'Account type chuniye',
    customerRoleBody: 'Job post kijiye, skilled labour dhoondhiye aur jaldi hire kijiye.',
    labourRoleBody: 'Profile, skill, availability aur matching jobs manage kijiye.',
    welcomeBack: 'Wapas swagat hai',
    createAccount: 'Account banaiye',
    loginDescription: 'Sirf zaroori details ke saath login kijiye aur seedha dashboard par jaiye.',
    signupDescription: 'Jaldi register kijiye aur apne role ke hisab se tools use kijiye.',
    fullName: 'Pura naam',
    fullNamePlaceholder: 'Apna pura naam likhiye',
    email: 'Email',
    emailPlaceholder: 'Apna email likhiye',
    phone: 'Mobile number',
    phonePlaceholder: 'Apna mobile number likhiye',
    password: 'Password',
    passwordPlaceholder: 'Apna password likhiye',
    submitLogin: 'Dashboard kholiye',
    submitSignup: 'Account banaiye',
    switchToLogin: 'Pehle se account hai? Login kijiye',
    switchToSignup: 'Account nahi hai? Signup kijiye',
    demoButton: 'Demo kholiye',
    back: 'Wapas',
    needWorkers: 'Mujhe workers chahiye',
    offerServices: 'Main service de sakta hoon',
    customerRoleDescription: 'Apni project details post kijiye aur quickly apne area ke millions workers, electricians, plumbers se connect kijiye.',
    labourRoleDescription: 'Apne kaam ka strong profile banaiye, apni skills highlight kijiye aur customers se discovered hote jaiye.',
    startHiring: 'Hiring Shuru Kijiye',
    signUpWorker: 'Worker ke taur par signup kijiye',
    allCitiesAvailable: 'Muzaffarpur me available hai',
    footerBenefits: 'Muzaffarpur me opportunities • Better worker-employer matching • Professional first impression',
    envTitle: 'Ek hi API configuration',
    envBody: '.env me EXPO_PUBLIC_API_URL set kijiye, fir sab API calls clean rahengi.',
    missingTitle: 'Jankari adhoori hai',
    missingBody: 'Aage badhne se pehle zaroori fields bhariye.',
    successTitle: 'Safal',
    loginSuccess: 'Login safal raha.',
    signupSuccess: 'Signup safal raha.',
    errorTitle: 'Request fail hui',
    logout: 'Logout',
    customerDashboardBadge: 'Customer Home',
    labourDashboardBadge: 'Labour Dashboard',
    hello: 'Namaste',
    customerSubtitle:
      'Skill, area aur availability ke hisab se labour dhoondhiye, phir simple flow me job post kijiye.',
    labourSubtitle:
      'Skill update rakhiye, profile saaf rakhiye aur Muzaffarpur ke matching jobs dekhiye.',
    activeLabours: 'Available labour',
    liveJobs: 'Live jobs',
    avgRating: 'Avg rating',
    hiresToday: 'Aaj hire',
    matchesToday: 'Aaj matching jobs',
    profileViews: 'Profile views',
    completedJobs: 'Completed jobs',
    responseRate: 'Response rate',
    filtersTitle: 'Filters',
    searchPlaceholder: 'Skill, naam ya area se search kijiye',
    district: 'Shehar / Area',
    category: 'Skill',
    availability: 'Availability',
    rating: 'Rating',
    clearFilters: 'Filters hataiye',
    availableLaboursTitle: 'Muzaffarpur me available labour',
    noLabours: 'Current filters me koi labour nahi mila.',
    popularSkillsTitle: 'Popular skills',
    postJobTitle: 'Job post kijiye',
    postJobOpen: 'Post Job',
    jobTitle: 'Job title',
    jobTitlePlaceholder: '2 ghante ke liye Raj Mistri chahiye',
    requiredSkill: 'Required skill',
    dateTime: 'Date aur time',
    dateTimePlaceholder: 'Aaj, 4:00 PM',
    locationLabel: 'Location',
    locationPlaceholder: 'Motijheel, Bela, Muzaffarpur...',
    description: 'Job description',
    descriptionPlaceholder: 'Kaam ka detail saaf likhiye',
    skillLevel: 'Skill level',
    postJobButton: 'Job Publish Karein',
    close: 'Band Karein',
    profileTitle: 'Labour profile',
    skillsTitle: 'Skills aur certifications',
    preferencesTitle: 'Availability aur preferences',
    reviewsTitle: 'Ratings aur reviews',
    workHistoryTitle: 'Work history',
    jobRequestsTitle: 'Labour ke liye posted jobs',
    availableJobsTitle: 'Available jobs',
    updateSkills: 'Skills Update',
    editProfile: 'Profile Edit',
    applicantsLabel: 'Applicants',
    postedLabel: 'Posted',
    distanceLabel: 'Distance',
    hireNow: 'Abhi Hire Karein',
    applyNow: 'Abhi Apply Karein',
    applied: 'Apply Ho Gaya',
    ratingLabel: 'Rating',
    save: 'Save Karein',
    cancel: 'Cancel Karein',
    namePlaceholder: 'Apna naam likhiye',
    titlePlaceholder: 'Apna job title likhiye',
    locationPlaceholder: 'Apna location likhiye',
    phonePlaceholder: 'Apna phone number likhiye',
    profileUpdatedTitle: 'Profile Update Ho Gaya',
    profileUpdatedMessage: 'Aapka profile successfully update ho gaya hai.',
    apply: 'Apply Karein',
    applyConfirmTitle: 'Job ke liye Apply Karein',
    applyConfirmMessage: 'Kya aap "{job}" ke liye apply karna chahte hain?',
    alreadyAppliedTitle: 'Pehle Hi Apply Ho Gaya',
    alreadyAppliedMessage: 'Aap is job ke liye already apply kar chuke hain.',
    applicationSuccessTitle: 'Application Submit Ho Gaya',
    applicationSuccessMessage: 'Aapki application successfully submit ho gayi hai.',
    applicationSubmitted: '{job} ke liye application submit ho gaya',
    todayWorkButton: 'Aaj Ka Kaam',
    todayWorkConfirmTitle: 'Aaj Ka Kaam Request Karein',
    todayWorkConfirmMessage: 'Aapka job offer 15 minute me confirm ho jayega. Continue?',
    confirm: 'Confirm Karein',
    todayWorkSuccessTitle: 'Request Submit Ho Gaya',
    todayWorkSuccessMessage: 'Aapka aaj ka kaam request submit ho gaya hai.',
    todayWorkNotification: 'Aaj ka kaam request submit - 15 minute me confirmation',
    notificationsTitle: 'Notifications',
    notifyTitle: 'Notifications',
    notifyCustomer: 'Jab labour reply kare, job accept ho, ya nearby labour available ho to alert paiye.',
    notifyLabour: 'Jab nayi job aapki skill aur time se match kare to alert paiye.',
    focusMuzaffarpur: 'Primary area: Muzaffarpur',
    focusMuzaffarpurBody:
      'Platform sabse pehle Muzaffarpur ke jobs aur labour ko highlight karta hai.',
    messengerTitle: 'Chat aur messages',
    messengerCustomer: 'Shortlist ya hire karne ke baad labour se seedha chat kijiye.',
    messengerLabour: 'Matching job milne par customer se seedha baat kijiye.',
    jobPostedTitle: 'Job post ho gayi',
    jobPostedBody: 'Aapki job ab nearby labour ko dikh rahi hai.',
    today: 'Aaj',
    tomorrow: 'Kal',
    specificDate: 'Specific Date',
  },
  bho: {
    badge: 'Muzaffarpur Labor Hub',
    headline: 'Muzaffarpur खातिर साफ अउर आसान काम-मजदूर प्लेटफॉर्म',
    subheadline:
      'Customer आ labour दुनो खातिर neat login, job post, matching, rating आ chat-ready section.',
    login: 'Login',
    signup: 'Signup',
    customer: 'Customer',
    labour: 'Labour',
    roleTitle: 'Account type चुनीं',
    customerRoleBody: 'Job post करीं, हुनरमंद labour खोजीं आ फटाफट hire करीं.',
    labourRoleBody: 'Apna profile, skill, availability आ matching job sambhaliं.',
    welcomeBack: 'फेरु से स्वागत बा',
    createAccount: 'Account बनाईं',
    loginDescription: 'बस जरूरी detail दीं आ सीधा dashboard पर चलीं.',
    signupDescription: 'जल्दी register करीं आ अपना role हिसाब से tool use करीं.',
    fullName: 'पूरा नाम',
    fullNamePlaceholder: 'अपना पूरा नाम लिखीं',
    email: 'Email',
    emailPlaceholder: 'अपना email लिखीं',
    phone: 'Mobile number',
    phonePlaceholder: 'अपना mobile number लिखीं',
    password: 'Password',
    passwordPlaceholder: 'अपना password लिखीं',
    submitLogin: 'Dashboard खोलीं',
    submitSignup: 'Account बनाईं',
    switchToLogin: 'पहिले से account बा? Login करीं',
    switchToSignup: 'Account नइखे? Signup करीं',
    demoButton: 'Demo खोलीं',
    back: 'वापस',
    needWorkers: 'मोहे मजदूर चाही',
    offerServices: 'हम सेवा दे सकिते बानी',
    customerRoleDescription: 'अपनो project details post करीं आ फटाफट अपने area के नए मजदूर, इलेक्ट्रीशियन, प्लंबर से जुड़ीं.',
    labourRoleDescription: 'अपनो काम का मजबूत profile बनाईं, अपनी skill दिखाईं आ customer के-ओ अपने से खोज करे दीं.',
    startHiring: 'Hiring शुरु करीं',
    signUpWorker: 'Worker के तउर पर signup करीं',
    allCitiesAvailable: 'Muzaffarpur में उपलब्ध बा',
    footerBenefits: 'Muzaffarpur में काम के मौका • अइसन worker-employer मिलान • Professional पहिली छाप',
    envTitle: 'एगो API setting',
    envBody: '.env में EXPO_PUBLIC_API_URL सेट करीं, फेर सब API call साफ रही.',
    missingTitle: 'जानकारी अधूरा बा',
    missingBody: 'आगे बढ़े से पहिले जरूरी field भर दीं.',
    successTitle: 'सफल',
    loginSuccess: 'Login सफल भइल.',
    signupSuccess: 'Signup सफल भइल.',
    errorTitle: 'Request fail भइल',
    logout: 'Logout',
    customerDashboardBadge: 'Customer Home',
    labourDashboardBadge: 'Labour Dashboard',
    hello: 'प्रणाम',
    customerSubtitle:
      'Skill, area आ availability देख के labour खोजीं, फेर आसान तरीका से job post करीं.',
    labourSubtitle:
      'Skill update राखीं, profile neat राखीं आ Muzaffarpur के matching job देखीं.',
    activeLabours: 'Available labour',
    liveJobs: 'Live jobs',
    avgRating: 'Avg rating',
    hiresToday: 'आज hire',
    matchesToday: 'आज match job',
    profileViews: 'Profile views',
    completedJobs: 'पूरा काम',
    responseRate: 'Response rate',
    filtersTitle: 'Filters',
    searchPlaceholder: 'Skill, naam या area से खोजीं',
    district: 'सहर / इलाका',
    category: 'Skill',
    availability: 'उपलब्धता',
    rating: 'Rating',
    clearFilters: 'Filter हटाईं',
    availableLaboursTitle: 'Muzaffarpur में available labour',
    noLabours: 'एह filter पर कौनों labour ना मिलल.',
    popularSkillsTitle: 'Popular skills',
    postJobTitle: 'Job post करीं',
    postJobOpen: 'Post Job',
    jobTitle: 'Job title',
    jobTitlePlaceholder: '2 घंटा खातिर Raj Mistri चाहीं',
    requiredSkill: 'Required skill',
    dateTime: 'Date अउर time',
    dateTimePlaceholder: 'आज, 4:00 PM',
    locationLabel: 'Location',
    locationPlaceholder: 'Motijheel, Bela, Muzaffarpur...',
    description: 'Job description',
    descriptionPlaceholder: 'काम के detail साफ-साफ लिखीं',
    skillLevel: 'Skill level',
    postJobButton: 'Job Publish करीं',
    close: 'बंद करीं',
    profileTitle: 'Labour profile',
    skillsTitle: 'Skills आ certification',
    preferencesTitle: 'उपलब्धता आ पसंद',
    reviewsTitle: 'Rating आ review',
    workHistoryTitle: 'काम के इतिहास',
    jobRequestsTitle: 'Labour खातिर posted job',
    availableJobsTitle: 'Available job',
    updateSkills: 'Skill Update',
    editProfile: 'Profile Edit',
    applicantsLabel: 'Applicants',
    postedLabel: 'Posted',
    distanceLabel: 'दूरी',
    hireNow: 'अभी Hire करीं',
    applyNow: 'अभी Apply करीं',
    applied: 'Apply हो गइल',
    ratingLabel: 'Rating',
    save: 'Save करीं',
    cancel: 'Cancel करीं',
    namePlaceholder: 'अपना नाम लिखीं',
    titlePlaceholder: 'अपना job title लिखीं',
    locationPlaceholder: 'अपना location लिखीं',
    phonePlaceholder: 'अपना phone number लिखीं',
    profileUpdatedTitle: 'Profile Update हो गइल',
    profileUpdatedMessage: 'रउरा profile सफलतापूर्वक update हो गइल बा.',
    apply: 'Apply करीं',
    applyConfirmTitle: 'Job खातिर Apply करीं',
    applyConfirmMessage: 'की रउवा "{job}" खातिर apply करना चाहत बानी?',
    alreadyAppliedTitle: 'पहिले ही Apply हो गइल',
    alreadyAppliedMessage: 'रउवा एह job खातिर पहिले ही apply कर चुके बानी.',
    applicationSuccessTitle: 'Application Submit हो गइल',
    applicationSuccessMessage: 'रउरा application सफलतापूर्वक submit हो गइल बा.',
    applicationSubmitted: '{job} खातिर application submit हो गइल',
    todayWorkButton: 'आज का काम',
    todayWorkConfirmTitle: 'आज का काम Request करीं',
    todayWorkConfirmMessage: 'रउरा job offer 15 मिनट में confirm हो जाई. जारी राखीं?',
    confirm: 'Confirm करीं',
    todayWorkSuccessTitle: 'Request Submit हो गइल',
    todayWorkSuccessMessage: 'रउरा आज का काम request submit हो गइल बा.',
    todayWorkNotification: 'आज का काम request submit - 15 मिनट में confirmation',
    notificationsTitle: 'Notifications',
    notifyTitle: 'Notification',
    notifyCustomer: 'जब labour जवाब दे, job accept होखे, या nearby labour available होखे त alert मिली.',
    notifyLabour: 'जब नया job रउरा skill आ time से match करी त alert मिली.',
    focusMuzaffarpur: 'मुख्य इलाका: Muzaffarpur',
    focusMuzaffarpurBody:
      'ई platform सबसे पहिले Muzaffarpur के labour आ job पर focus करेला.',
    messengerTitle: 'Chat आ message',
    messengerCustomer: 'Shortlist या hire कइला के बाद labour से सीधा बतिआईं.',
    messengerLabour: 'Matching job मिलते customer से सीधा बात करीं.',
    jobPostedTitle: 'Job post हो गइल',
    jobPostedBody: 'रउरा job अब nearby labour लोग देख सकत बा.',
    today: 'आज',
    tomorrow: 'काल्ह',
    specificDate: 'Fix date',
  },
};
