export const copy = {
  en: {
    address: 'Address',
    addressPlaceholder: 'Enter your address',
    badge: ' Labor Hub',
    headline: 'Simple hiring and job matching for ',
    subheadline:
      'A clean customer and labour platform with Bhojpuri, Hindi, posting, matching, ratings, and chat-ready sections.',
    login: 'Login',
    signup: 'Sign Up',
    customer: 'Customer',
    labour: 'Labour',
    roleTitle: 'Choose account type',
    customerRoleBody: 'Post jobs, find skilled labour, and hire faster.',
    labourRoleBody: 'Manage profile, skills, availability, and matching jobs.',
    welcomeBack: 'Welcome back',
    createAccount: 'Create account',
    loginDescription: 'Login with only the essential details and go straight to your dashboard.',
    signupDescription: 'Register quickly and continue with the right tools for your role.',
    fullName: 'Full name',
    fullNamePlaceholder: 'Enter your full name',
    email: 'Email address',
    emailPlaceholder: 'Enter your email',
    phone: 'Phone number',
    phonePlaceholder: 'Enter your phone number',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    submitLogin: 'Open Dashboard',
    submitSignup: 'Create Account',
    switchToLogin: 'Already have an account? Login',
    switchToSignup: 'Need an account? Create one',
    demoButton: 'Open Demo',
    back: 'Back',
    needWorkers: 'I need workers',
    offerServices: 'I offer services',
    customerRoleDescription: 'Post your project details and quickly connect with millions, helpers, electricians, plumbers, and more in your area.',
    labourRoleDescription: 'Build a strong profile for your work, highlight your skills, and get discovered by customers looking for reliable local professionals.',
    startHiring: 'Start Hiring',
    signUpWorker: 'Sign up as a worker',
    allCitiesAvailable: 'Available in ',
    footerBenefits: 'Live opportunities in  • Better worker-employer matching • Professional first impression',
    envTitle: 'Single API configuration',
    envBody: 'Set EXPO_PUBLIC_API_URL once in your .env file and keep your API calls clean.',
    missingTitle: 'Missing information',
    missingBody: 'Please fill the required fields before continuing.',
    successTitle: 'Success',
    loginSuccess: 'Login completed successfully.',
    signupSuccess: 'Signup completed successfully.',
    errorTitle: 'Request failed',
    logout: 'Logout',
    customerDashboardBadge: 'Customer Home',
    labourDashboardBadge: 'Labour Dashboard',
    hello: 'Hello',
    customerSubtitle:
      'Search labour by skill, area, and availability, then post work in a clean simple flow.',
    labourSubtitle:
      'Update skills, keep your profile neat, and browse matching jobs near .',
    activeLabours: 'Available labour',
    liveJobs: 'Live jobs',
    avgRating: 'Avg rating',
    hiresToday: 'Hires today',
    jobsCompleted: 'Jobs completed',
    pendingRequests: 'Pending requests',
    matchesToday: 'Matches today',
    profileViews: 'Profile views',
    completedJobs: 'Completed jobs',
    responseRate: 'Response rate',
    filtersTitle: 'Filters',
    searchPlaceholder: 'Search by skill, name, or area',
    district: 'City / Area',
    category: 'Skill',
    availability: 'Availability',
    rating: 'Rating',
    clearFilters: 'Clear filters',
    availableLaboursTitle: 'Available labour in ',
    noLabours: 'No labour found for the current filters.',
    popularSkillsTitle: 'Popular skills',
    postJobTitle: 'Post a job',
    postJobOpen: 'Post Job',
    jobTitle: 'Job title',
    jobTitlePlaceholder: 'Need Raj Mistri for 2 hours',
    requiredSkill: 'Required skill',
    dateTime: 'Date and time',
    dateTimePlaceholder: 'Today, 4:00 PM',
    locationLabel: 'Location',
    locationPlaceholder: 'Motijheel, Bela, ...',
    description: 'Job description',
    descriptionPlaceholder: 'Write the work details clearly',
    skillLevel: 'Skill level',
    postJobButton: 'Publish Job',
    close: 'Close',
    profileTitle: 'Labour profile',
    skillsTitle: 'Skills and certifications',
    preferencesTitle: 'Availability and preferences',
    reviewsTitle: 'Ratings and reviews',
    workHistoryTitle: 'Work history',
    jobRequestsTitle: 'Posted jobs for labour',
    availableJobsTitle: 'Available jobs',
    updateSkills: 'Update Skills',
    editProfile: 'Edit Profile',
    applicantsLabel: 'Applicants',
    postedLabel: 'Posted',
    distanceLabel: 'Distance',
    hireNow: 'Hire Now',
    applyNow: 'Apply Now',
    applied: 'Applied',
    ratingLabel: 'Rating',
    save: 'Save',
    cancel: 'Cancel',
    namePlaceholder: 'Enter your name',
    titlePlaceholder: 'Enter your job title',

    profileUpdatedTitle: 'Profile Updated',
    profileUpdatedMessage: 'Your profile has been updated successfully.',
    apply: 'Apply',
    applyConfirmTitle: 'Apply for Job',
    applyConfirmMessage: 'Are you sure you want to apply for "{job}"?',
    alreadyAppliedTitle: 'Already Applied',
    alreadyAppliedMessage: 'You have already applied for this job.',
    applicationSuccessTitle: 'Application Submitted',
    applicationSuccessMessage: 'Your application has been submitted successfully.',
    applicationSubmitted: 'Application submitted for {job}',
    todayWorkButton: 'Today Work',
    todayWorkConfirmTitle: 'Request Today Work',
    todayWorkConfirmMessage: 'Your job offer will be confirmed within 15 minutes. Continue?',
    confirm: 'Confirm',
    todayWorkSuccessTitle: 'Request Submitted',
    todayWorkSuccessMessage: 'Your today work request has been submitted.',
    todayWorkNotification: 'Today work request submitted - confirmation within 15 minutes',
    notificationsTitle: 'Notifications',
    notifyTitle: 'Notifications',
    notifyCustomer: 'Get alerts when a labour responds, job is accepted, or someone becomes available nearby.',
    notifyLabour: 'Get alerts when a new job matches your skill and preferred time.',
    focus: 'Primary area: ',
    focusBody:
      'The platform highlights jobs and labour around  first, with simple city-based filters.',
    messengerTitle: 'Chat and messages',
    messengerCustomer: 'Chat directly with labour after shortlisting or hiring.',
    messengerLabour: 'Reply to customers directly when jobs match your skill.',
    jobPostedTitle: 'Job posted',
    jobPostedBody: 'Your job is now visible for nearby labour.',
    today: 'Today',
    tomorrow: 'Tomorrow',
    specificDate: 'Specific Date',
    focusMuzaffarpur: 'Primary area: ',
    focusMuzaffarpurBody:
      'The platform highlights jobs and labour around first, with simple city-based filters.',
  },
  address: 'Address',
  addressPlaceholder: 'Enter your address',
  hi: {
    address: 'पता',
    addressPlaceholder: 'अपना पता लिखिए',
    badge: 'लेबर हब',
    headline: 'के लिए आसान और साफ़ भर्ती प्लेटफ़ॉर्म',
    subheadline:
      'कस्टमर और लेबर दोनों के लिए आसान लॉगिन, जॉब पोस्टिंग, मैचिंग, रेटिंग और चैट की सुविधा।',

    login: 'लॉगिन',
    signup: 'साइन अप',
    customer: 'कस्टमर',
    pendingRequests: 'लंबित अनुरोध',
    labour: 'लेबर',

    roleTitle: 'अकाउंट का प्रकार चुनें',
    customerRoleBody: 'जॉब पोस्ट करें, कुशल लेबर खोजें और जल्दी हायर करें।',
    labourRoleBody: 'अपना प्रोफाइल, स्किल और उपलब्धता मैनेज करें।',

    welcomeBack: 'वापसी पर स्वागत है',
    createAccount: 'अकाउंट बनाएं',

    loginDescription: 'ज़रूरी जानकारी के साथ लॉगिन करें और सीधे डैशबोर्ड पर जाएं।',
    signupDescription: 'जल्दी रजिस्टर करें और अपने रोल के अनुसार टूल्स का उपयोग करें।',

    fullName: 'पूरा नाम',
    fullNamePlaceholder: 'अपना पूरा नाम लिखें',
    email: 'ईमेल',
    emailPlaceholder: 'अपना ईमेल लिखें',
    phone: 'मोबाइल नंबर',
    phonePlaceholder: 'अपना मोबाइल नंबर लिखें',
    password: 'पासवर्ड',
    passwordPlaceholder: 'अपना पासवर्ड लिखें',

    submitLogin: 'डैशबोर्ड खोलें',
    submitSignup: 'अकाउंट बनाएं',

    switchToLogin: 'पहले से अकाउंट है? लॉगिन करें',
    switchToSignup: 'अकाउंट नहीं है? साइन अप करें',

    demoButton: 'डेमो देखें',
    back: 'वापस',

    needWorkers: 'मुझे वर्कर चाहिए',
    offerServices: 'मैं सेवा दे सकता हूँ',

    customerRoleDescription:
      'अपनी प्रोजेक्ट डिटेल पोस्ट करें और अपने क्षेत्र के वर्कर्स, इलेक्ट्रीशियन, प्लंबर से जुड़ें।',
    labourRoleDescription:
      'अपना मजबूत प्रोफाइल बनाएं, स्किल दिखाएं और कस्टमर से जुड़ें।',

    startHiring: 'हायरिंग शुरू करें',
    signUpWorker: 'वर्कर के रूप में साइन अप करें',

    allCitiesAvailable: 'में उपलब्ध है',
    footerBenefits:
      'में अवसर • बेहतर वर्कर-एम्प्लॉयर मैचिंग • प्रोफेशनल पहली छाप',

    envTitle: 'एक ही API कॉन्फ़िगरेशन',
    envBody: '.env में EXPO_PUBLIC_API_URL सेट करें, सभी API कॉल्स आसान हो जाएंगी।',

    missingTitle: 'जानकारी अधूरी है',
    missingBody: 'आगे बढ़ने से पहले सभी ज़रूरी फ़ील्ड भरें।',

    successTitle: 'सफल',
    loginSuccess: 'लॉगिन सफल रहा।',
    signupSuccess: 'साइन अप सफल रहा।',

    errorTitle: 'रिक्वेस्ट असफल रही',
    logout: 'लॉगआउट',

    customerDashboardBadge: 'कस्टमर होम',
    labourDashboardBadge: 'लेबर डैशबोर्ड',

    hello: 'नमस्ते',

    customerSubtitle:
      'स्किल, क्षेत्र और उपलब्धता के अनुसार लेबर खोजें और आसानी से जॉब पोस्ट करें।',
    labourSubtitle:
      'अपनी स्किल अपडेट रखें और मैचिंग जॉब्स देखें।',

    activeLabours: 'उपलब्ध लेबर',
    liveJobs: 'चल रही जॉब्स',
    avgRating: 'औसत रेटिंग',
    hiresToday: 'आज हायर',
    matchesToday: 'आज की मैचिंग जॉब्स',

    profileViews: 'प्रोफाइल व्यू',
    completedJobs: 'पूर्ण जॉब्स',
    responseRate: 'रिस्पॉन्स रेट',

    filtersTitle: 'फ़िल्टर',
    searchPlaceholder: 'स्किल, नाम या क्षेत्र से खोजें',
    district: 'शहर / क्षेत्र',
    category: 'स्किल',
    availability: 'उपलब्धता',
    rating: 'रेटिंग',
    clearFilters: 'फ़िल्टर हटाएं',

    availableLaboursTitle: 'में उपलब्ध लेबर',
    noLabours: 'इस फ़िल्टर में कोई लेबर नहीं मिला।',

    popularSkillsTitle: 'लोकप्रिय स्किल्स',

    postJobTitle: 'जॉब पोस्ट करें',
    postJobOpen: 'जॉब पोस्ट करें',

    jobTitle: 'जॉब शीर्षक',
    jobTitlePlaceholder: '2 घंटे के लिए राज मिस्त्री चाहिए',

    requiredSkill: 'आवश्यक स्किल',
    dateTime: 'तारीख और समय',
    dateTimePlaceholder: 'आज, 4:00 PM',

    locationLabel: 'लोकेशन',
    locationPlaceholder: 'मोतीझील, बेला, ...',

    description: 'जॉब विवरण',
    descriptionPlaceholder: 'काम का विवरण साफ़ लिखें',

    skillLevel: 'स्किल स्तर',

    postJobButton: 'जॉब प्रकाशित करें',
    close: 'बंद करें',

    profileTitle: 'लेबर प्रोफाइल',
    skillsTitle: 'स्किल्स और सर्टिफिकेट',
    preferencesTitle: 'उपलब्धता और प्राथमिकताएं',
    reviewsTitle: 'रेटिंग और रिव्यू',
    workHistoryTitle: 'कार्य इतिहास',

    jobRequestsTitle: 'लेबर के लिए जॉब्स',
    availableJobsTitle: 'उपलब्ध जॉब्स',

    updateSkills: 'स्किल अपडेट करें',
    editProfile: 'प्रोफाइल एडिट करें',

    applicantsLabel: 'आवेदक',
    postedLabel: 'पोस्ट किया गया',
    distanceLabel: 'दूरी',

    hireNow: 'अभी हायर करें',
    applyNow: 'अभी आवेदन करें',
    applied: 'आवेदन हो गया',

    ratingLabel: 'रेटिंग',

    save: 'सेव करें',
    cancel: 'रद्द करें',

    namePlaceholder: 'अपना नाम लिखें',
    titlePlaceholder: 'अपना जॉब टाइटल लिखें',

    profileUpdatedTitle: 'प्रोफाइल अपडेट हो गया',
    profileUpdatedMessage: 'आपका प्रोफाइल सफलतापूर्वक अपडेट हो गया है।',

    apply: 'आवेदन करें',

    applyConfirmTitle: 'जॉब के लिए आवेदन करें',
    applyConfirmMessage: 'क्या आप "{job}" के लिए आवेदन करना चाहते हैं?',

    alreadyAppliedTitle: 'पहले ही आवेदन हो चुका है',
    alreadyAppliedMessage: 'आप इस जॉब के लिए पहले ही आवेदन कर चुके हैं।',

    applicationSuccessTitle: 'आवेदन सफल',
    applicationSuccessMessage: 'आपका आवेदन सफलतापूर्वक जमा हो गया है।',

    applicationSubmitted: '{job} के लिए आवेदन जमा हो गया',

    todayWorkButton: 'आज का काम',
    todayWorkConfirmTitle: 'आज का काम अनुरोध करें',
    todayWorkConfirmMessage: 'आपका जॉब ऑफर 15 मिनट में कन्फर्म हो जाएगा। जारी रखें?',

    confirm: 'कन्फर्म करें',

    todayWorkSuccessTitle: 'अनुरोध सफल',
    todayWorkSuccessMessage: 'आपका अनुरोध सफलतापूर्वक भेज दिया गया है।',

    todayWorkNotification: 'आज का काम अनुरोध भेजा गया - 15 मिनट में कन्फर्मेशन',

    notificationsTitle: 'नोटिफिकेशन',
    notifyTitle: 'नोटिफिकेशन',

    notifyCustomer:
      'जब लेबर जवाब दे, जॉब स्वीकार करे या आसपास लेबर उपलब्ध हो तो सूचना पाएं।',
    notifyLabour:
      'जब नई जॉब आपकी स्किल से मेल खाए तो सूचना पाएं।',

    focus: 'मुख्य क्षेत्र: ',
    focusBody:
      'प्लेटफ़ॉर्म पहले आसपास के जॉब्स और लेबर को दिखाता है।',

    messengerTitle: 'चैट और संदेश',
    messengerCustomer:
      'हायर करने के बाद सीधे लेबर से चैट करें।',
    messengerLabour:
      'मैचिंग जॉब मिलने पर कस्टमर से सीधे बात करें।',

    jobPostedTitle: 'जॉब पोस्ट हो गई',
    jobPostedBody: 'आपकी जॉब अब आसपास के लेबर को दिखाई दे रही है।',

    today: 'आज',
    tomorrow: 'कल',
    specificDate: 'विशिष्ट तारीख',

    focusMuzaffarpur: 'मुख्य क्षेत्र: ',
    focusMuzaffarpurBody:
      'प्लेटफ़ॉर्म पहले आसपास के जॉब्स और लेबर को दिखाता है।',
  },
  bho: {
    address: 'पता',
    addressPlaceholder: 'अपना पता लिखीं',
    badge: ' Labor Hub',
    headline: ' खातिर साफ अउर आसान काम-मजदूर प्लेटफॉर्म',
    subheadline:
      'Customer आ labour दुनो खातिर neat login, job post, matching, rating आ chat-ready section.',
    login: 'Login',
    signup: 'Signup',
    customer: 'Customer',
    labour: 'Labour',
    roleTitle: 'Account type चुनीं',
    customerRoleBody: 'Job post करीं, हुनरमंद labour खोजीं आ फटाफट hire करीं.',
    labourRoleBody: 'Apna profile, skill, availability आ matching job sambhaliं.',
    welcomeBack: 'फेरु से स्वागत बा',
    createAccount: 'Account बनाईं',
    loginDescription: 'बस जरूरी detail दीं आ सीधा dashboard पर चलीं.',
    signupDescription: 'जल्दी register करीं आ अपना role हिसाब से tool use करीं.',
    fullName: 'पूरा नाम',
    fullNamePlaceholder: 'अपना पूरा नाम लिखीं',
    email: 'Email',
    emailPlaceholder: 'अपना email लिखीं',
    phone: 'Mobile number',
    phonePlaceholder: 'अपना mobile number लिखीं',
    password: 'Password',
    passwordPlaceholder: 'अपना password लिखीं',
    submitLogin: 'Dashboard खोलीं',
    submitSignup: 'Account बनाईं',
    switchToLogin: 'पहिले से account बा? Login करीं',
    switchToSignup: 'Account नइखे? Signup करीं',
    demoButton: 'Demo खोलीं',
    back: 'वापस',
    pendingRequests: 'बाकी बांचल रिक्वेस्ट',
    needWorkers: 'मोहे मजदूर चाही',
    offerServices: 'हम सेवा दे सकिते बानी',
    customerRoleDescription: 'अपनो project details post करीं आ फटाफट अपने area के नए मजदूर, इलेक्ट्रीशियन, प्लंबर से जुड़ीं.',
    labourRoleDescription: 'अपनो काम का मजबूत profile बनाईं, अपनी skill दिखाईं आ customer के-ओ अपने से खोज करे दीं.',
    startHiring: 'Hiring शुरु करीं',
    signUpWorker: 'Worker के तउर पर signup करीं',
    allCitiesAvailable: ' में उपलब्ध बा',
    footerBenefits: ' में काम के मौका • अइसन worker-employer मिलान • Professional पहिली छाप',
    envTitle: 'एगो API setting',
    envBody: '.env में EXPO_PUBLIC_API_URL सेट करीं, फेर सब API call साफ रही.',
    missingTitle: 'जानकारी अधूरा बा',
    missingBody: 'आगे बढ़े से पहिले जरूरी field भर दीं.',
    successTitle: 'सफल',
    loginSuccess: 'Login सफल भइल.',
    signupSuccess: 'Signup सफल भइल.',
    errorTitle: 'Request fail भइल',
    logout: 'Logout',
    customerDashboardBadge: 'Customer Home',
    labourDashboardBadge: 'Labour Dashboard',
    hello: 'प्रणाम',
    customerSubtitle:
      'Skill, area आ availability देख के labour खोजीं, फेर आसान तरीका से job post करीं.',
    labourSubtitle:
      'Skill update राखीं, profile neat राखीं आ  के matching job देखीं.',
    activeLabours: 'Available labour',
    liveJobs: 'Live jobs',
    avgRating: 'Avg rating',
    hiresToday: 'आज hire',
    matchesToday: 'आज match job',
    profileViews: 'Profile views',
    completedJobs: 'पूरा काम',
    responseRate: 'Response rate',
    filtersTitle: 'Filters',
    searchPlaceholder: 'Skill, naam या area से खोजीं',
    district: 'सहर / इलाका',
    category: 'Skill',
    availability: 'उपलब्धता',
    rating: 'Rating',
    clearFilters: 'Filter हटाईं',
    availableLaboursTitle: ' में available labour',
    noLabours: 'एह filter पर कौनों labour ना मिलल.',
    popularSkillsTitle: 'Popular skills',
    postJobTitle: 'Job post करीं',
    postJobOpen: 'Post Job',
    jobTitle: 'Job title',
    jobTitlePlaceholder: '2 घंटा खातिर Raj Mistri चाहीं',
    requiredSkill: 'Required skill',
    dateTime: 'Date अउर time',
    dateTimePlaceholder: 'आज, 4:00 PM',
    locationLabel: 'Location',
    locationPlaceholder: 'Motijheel, Bela, ...',
    description: 'Job description',
    descriptionPlaceholder: 'काम के detail साफ-साफ लिखीं',
    skillLevel: 'Skill level',
    postJobButton: 'Job Publish करीं',
    close: 'बंद करीं',
    profileTitle: 'Labour profile',
    skillsTitle: 'Skills आ certification',
    preferencesTitle: 'उपलब्धता आ पसंद',
    reviewsTitle: 'Rating आ review',
    workHistoryTitle: 'काम के इतिहास',
    jobRequestsTitle: 'Labour खातिर posted job',
    availableJobsTitle: 'Available job',
    updateSkills: 'Skill Update',
    editProfile: 'Profile Edit',
    applicantsLabel: 'Applicants',
    postedLabel: 'Posted',
    distanceLabel: 'दूरी',
    hireNow: 'अभी Hire करीं',
    applyNow: 'अभी Apply करीं',
    applied: 'Apply हो गइल',
    ratingLabel: 'Rating',
    save: 'Save करीं',
    cancel: 'Cancel करीं',
    namePlaceholder: 'अपना नाम लिखीं',
    titlePlaceholder: 'अपना job title लिखीं',

    profileUpdatedTitle: 'Profile Update हो गइल',
    profileUpdatedMessage: 'रउरा profile सफलतापूर्वक update हो गइल बा.',
    apply: 'Apply करीं',
    applyConfirmTitle: 'Job खातिर Apply करीं',
    applyConfirmMessage: 'की रउवा "{job}" खातिर apply करना चाहत बानी?',
    alreadyAppliedTitle: 'पहिले ही Apply हो गइल',
    alreadyAppliedMessage: 'रउवा एह job खातिर पहिले ही apply कर चुके बानी.',
    applicationSuccessTitle: 'Application Submit हो गइल',
    applicationSuccessMessage: 'रउरा application सफलतापूर्वक submit हो गइल बा.',
    applicationSubmitted: '{job} खातिर application submit हो गइल',
    todayWorkButton: 'आज का काम',
    todayWorkConfirmTitle: 'आज का काम Request करीं',
    todayWorkConfirmMessage: 'रउरा job offer 15 मिनट में confirm हो जाई. जारी राखीं?',
    confirm: 'Confirm करीं',
    todayWorkSuccessTitle: 'Request Submit हो गइल',
    todayWorkSuccessMessage: 'रउरा आज का काम request submit हो गइल बा.',
    todayWorkNotification: 'आज का काम request submit - 15 मिनट में confirmation',
    notificationsTitle: 'Notifications',
    notifyTitle: 'Notification',
    notifyCustomer: 'जब labour जवाब दे, job accept होखे, या nearby labour available होखे त alert मिली.',
    notifyLabour: 'जब नया job रउरा skill आ time से match करी त alert मिली.',
    focus: 'मुख्य इलाका: ',
    focusBody:
      'ई platform सबसे पहिले  के labour आ job पर focus करेला.',
    messengerTitle: 'Chat आ message',
    messengerCustomer: 'Shortlist या hire कइला के बाद labour से सीधा बतिआईं.',
    messengerLabour: 'Matching job मिलते customer से सीधा बात करीं.',
    jobPostedTitle: 'Job post हो गइल',
    jobPostedBody: 'रउरा job अब nearby labour लोग देख सकत बा.',
    today: 'आज',
    tomorrow: 'काल्ह',
    specificDate: 'Fix date',
    focusMuzaffarpur: 'मुख्य क्षेत्र: ',
    focusMuzaffarpurBody:
      'यह प्लेटफ़ॉर्म पहले  के श्रमिकों और नौकरियों पर ध्यान केंद्रित करता है, जिसमें आसान शहर-आधारित फ़िल्टर होते हैं।',

  },
};
