import { StyleSheet } from 'react-native';

import { colors } from '../../theme/tokens';

export const styles = StyleSheet.create({
  container: {
    padding: 20,
    paddingBottom: 36,
    gap: 18,
  },
  hero: {
    backgroundColor: '#0c3b34',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    gap: 14,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  heroTop: {
    gap: 8,
  },
  heroTopActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  heroBody: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  heroCopy: {
    flex: 1,
    gap: 3,
  },
  badgeWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    backgroundColor: '#f5a623',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  heroBadge: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
  },
  logoutPill: {
    backgroundColor: '#ffffff',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  logoutPillText: {
    color: '#35554d',
    fontSize: 11,
    fontWeight: '700',
  },
  heroHello: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 19,
  },
  heroName: {
    color: '#54d7a0',
    fontSize: 31,
    fontWeight: '800',
    lineHeight: 35,
  },
  heroSubtitle: {
    color: 'rgba(232, 243, 239, 0.78)',
    fontSize: 11,
    lineHeight: 16,
    maxWidth: 185,
  },
  heroAvatarWrap: {
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  heroAvatarCircle: {
    width: 66,
    height: 66,
    borderRadius: 33,
    borderWidth: 2,
    borderColor: '#f3f0e8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroAvatarLetter: {
    color: '#f8f7f0',
    fontSize: 31,
    fontWeight: '700',
  },
  heroAvatarEdit: {
    position: 'absolute',
    right: 2,
    bottom: 5,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactCard: {
    backgroundColor: 'rgba(255,255,255,0.10)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 13,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.04)',
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  contactText: {
    color: 'rgba(255,255,255,0.88)',
    fontSize: 11,
    fontWeight: '500',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 12,
    columnGap: 6,
  },
  postJobBar: {
    backgroundColor: colors.panel,
    borderRadius: 12,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  postJobLabel: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  postJobBody: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  postJobAction: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  sectionCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: '#e6ece8',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  sectionTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sectionTitle: {
    color: '#273632',
    fontSize: 12,
    fontWeight: '700',
  },
  countBadge: {
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#e0efe8',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  countBadgeText: {
    color: '#0c5a49',
    fontSize: 10,
    fontWeight: '700',
  },
  jobsList: {
    gap: 12,
  },
  emptyCard: {
    backgroundColor: '#f6fbf8',
    borderRadius: 14,
    padding: 18,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2eee8',
  },
  emptyText: {
    color: '#5d726a',
    fontSize: 12,
    textAlign: 'center',
  },
  msgList: {
    gap: 10,
  },
  msgItem: {
    backgroundColor: '#f6fbf8',
    borderRadius: 14,
    padding: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: '#e2eee8',
  },
  msgHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  msgName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111',
  },
  msgStatus: {
    fontSize: 11,
    fontWeight: '700',
    color: '#16a34a',
  },
  msgText: {
    fontSize: 12,
    color: '#4b5563',
    lineHeight: 16,
  },
  skillRowGradient: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  skillChipGradient: {
    backgroundColor: '#edf5f1',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
  },
  skillTextGradient: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#325048',
  },
});
